on: 
  push:
    branches:
      - master
name: 🚀 Deploy website on push
jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.SSH_USER}}
        key: ${{secrets.SSH_PRIVATE_KEY}}
        port: ${{secrets.PORT}}
        script: |
          cd /var/www/adviist.com/public_html
          git pull origin master
          git status
          mv lv-demo-pages/* .
          rm -rf lv-demo-pages

        